version: "3.8"

services:
  nginx-sport:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/sport
      - ./docker/nginx/sport.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/sport
    container_name: nginx-sport
    depends_on:
      - php7.4-fpm-sport
    networks:
      - network-sport

  php7.4-fpm-sport:
    build:
      context: docker/php-fpm
      args:
        PUID: 1000
        PGID: 1000
        USER: user
    volumes:
      - ./:/var/www/sport
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/sport
    container_name: php7.4-fpm-sport
    user: "1000:1000"
    depends_on:
      - db-sport
    networks:
      - network-sport

  db-sport:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - persistent:/var/lib/mysql
    container_name: db-sport
    networks:
      - network-sport

volumes:
  persistent:
    name: volume-sport

networks:
  network-sport:
    driver: bridge
    name: network-sport