version: "3.8"

services:
  nginx_sport:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/sport
      - ./docker/nginx/sport.conf:/etc/nginx/conf.d/default.conf
    container_name: sport-nginx
    networks:
      - sport-network
    depends_on:
      - php7.2-fpm

  php7.2-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www/sport
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    container_name: sport-php7.2-fpm
    networks:
      - sport-network
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - persistent:/var/lib/mysql
    container_name: sport-db
    networks:
      - sport-network

volumes:
  persistent:
    name: sport-volume

networks:
  sport-network:
    driver: bridge
    name: sport-network